package redshift

import (
	"context"
	"errors"
	"strings"
	"testing"

	"devcloud/internal/services/redshift/backend"
	"devcloud/internal/services/redshift/backend/memory"
	"devcloud/internal/services/redshift/translator"
)

func TestSQLBackendInterfaceDefaultsToMemoryFallback(t *testing.T) {
	server := NewServer(Config{Database: "dev", User: "dev"})

	result, err := server.backend.Exec(context.Background(), "select 1")
	if err != nil {
		t.Fatalf("Exec(select 1) error = %v", err)
	}
	if result.Tag != "SELECT 1" || len(result.Rows) != 1 || result.Rows[0][0] != "1" {
		t.Fatalf("result = %#v", result)
	}
}

func TestMemoryBackendCatalogReflectsRedshiftMetadata(t *testing.T) {
	server := NewServer(Config{Database: "dev", User: "dev"})
	if _, err := server.executeSQL("create table events(id int, payload varchar(64)) diststyle key distkey(id) sortkey(id)"); err != nil {
		t.Fatalf("create table: %v", err)
	}

	catalog, err := server.backend.Catalog(context.Background())
	if err != nil {
		t.Fatalf("Catalog() error = %v", err)
	}
	table := findBackendTable(catalog, "public", "events")
	if table == nil {
		t.Fatalf("catalog missing public.events: %#v", catalog)
	}
	if len(table.Columns) != 2 || table.Columns[0].Name != "id" || table.Columns[1].Name != "payload" {
		t.Fatalf("columns = %#v", table.Columns)
	}
}

func TestMemoryBackendRejectsExecAfterClose(t *testing.T) {
	backend := memory.New(func(ctx context.Context, statement string) (backend.Result, error) {
		return backend.Result{Tag: "SELECT 1"}, nil
	}, nil)
	if err := backend.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}

	if _, err := backend.Exec(context.Background(), "select 1"); err == nil {
		t.Fatal("Exec after Close() error = nil")
	}
}

func TestSQLBackendCanBeInjected(t *testing.T) {
	expectedErr := errors.New("backend unavailable")
	server := NewServer(Config{SQLBackend: failingBackend{err: expectedErr}})

	if _, err := server.executeSQL("select 1"); !errors.Is(err, expectedErr) {
		t.Fatalf("executeSQL error = %v, want %v", err, expectedErr)
	}
}

func TestRedshiftTranslatorDefaultsToPassthrough(t *testing.T) {
	server := NewServer(Config{Database: "dev", User: "dev"})

	result, err := server.executeSQL("select 1")
	if err != nil {
		t.Fatalf("executeSQL(select 1) error = %v", err)
	}
	if result.tag != "SELECT 1" || len(result.rows) != 1 || result.rows[0][0] != "1" {
		t.Fatalf("result = %#v", result)
	}
}

func TestRedshiftTranslatorCanRewriteBackendSQL(t *testing.T) {
	server := NewServer(Config{
		Database:   "dev",
		User:       "dev",
		Translator: rewriteTranslator{backendSQL: "select 2"},
	})

	result, err := server.executeSQL("select 1")
	if err != nil {
		t.Fatalf("executeSQL(select 1) error = %v", err)
	}
	if len(result.rows) != 1 || result.rows[0][0] != "2" {
		t.Fatalf("rows = %#v", result.rows)
	}
}

func TestRedshiftTranslatorRejectsUnwiredSideEffects(t *testing.T) {
	server := NewServer(Config{
		Translator: rewriteTranslator{
			backendSQL: "select 1",
			sideEffects: []translator.SideEffect{
				{Kind: translator.SideEffectCopy, Source: "s3://bucket/key", Target: "public.events"},
			},
		},
	})

	if _, err := server.executeSQL("copy public.events from 's3://bucket/key' csv"); err == nil {
		t.Fatal("executeSQL with side effects error = nil")
	}
}

func TestRedshiftTranslatorExtractsTableAttributesForPostgresBackend(t *testing.T) {
	backend := &recordingBackend{result: backend.Result{Tag: "CREATE TABLE"}}
	server := NewServer(Config{
		SQLBackend: backend,
		Translator: translator.NewRedshiftToPostgres(),
	})

	_, err := server.executeSQL(`create table analytics.events(
		id integer identity(1,1) distkey sortkey encode raw,
		payload varchar(64) default 'unknown'
	) diststyle key distkey(id) sortkey(id) backup no`)
	if err != nil {
		t.Fatalf("executeSQL(create table) error = %v", err)
	}
	if strings.Contains(strings.ToLower(backend.statement), "diststyle") ||
		strings.Contains(strings.ToLower(backend.statement), "distkey") ||
		strings.Contains(strings.ToLower(backend.statement), "sortkey") ||
		strings.Contains(strings.ToLower(backend.statement), "encode") ||
		strings.Contains(strings.ToLower(backend.statement), "backup") {
		t.Fatalf("backend SQL still contains Redshift-only attributes: %s", backend.statement)
	}
	if !strings.Contains(strings.ToLower(backend.statement), "generated by default as identity") {
		t.Fatalf("backend SQL did not rewrite identity: %s", backend.statement)
	}

	catalog := server.CatalogSnapshot()
	if len(catalog.Tables) != 1 || catalog.Tables[0].Schema != "analytics" || catalog.Tables[0].DistStyle != "key" || catalog.Tables[0].DistKey != "id" {
		t.Fatalf("table metadata = %#v", catalog.Tables)
	}
	if len(catalog.Tables[0].SortKeys) != 1 || catalog.Tables[0].SortKeys[0] != "id" {
		t.Fatalf("sort keys = %#v", catalog.Tables[0].SortKeys)
	}
	if !columnSnapshotHas(catalog.Columns, "id", "raw", "", true) {
		t.Fatalf("id column metadata = %#v", catalog.Columns)
	}
	if !columnSnapshotHas(catalog.Columns, "payload", "", "'unknown'", false) {
		t.Fatalf("payload column metadata = %#v", catalog.Columns)
	}
}

func findBackendTable(catalog backend.CatalogSnapshot, schemaName string, tableName string) *backend.Table {
	for _, schema := range catalog.Schemas {
		if schema.Name != schemaName {
			continue
		}
		for i := range schema.Tables {
			if schema.Tables[i].Name == tableName {
				return &schema.Tables[i]
			}
		}
	}
	return nil
}

type failingBackend struct {
	err error
}

func (b failingBackend) Exec(ctx context.Context, statement string) (backend.Result, error) {
	return backend.Result{}, b.err
}

func (b failingBackend) Begin(ctx context.Context) (backend.Transaction, error) {
	return nil, b.err
}

func (b failingBackend) Catalog(ctx context.Context) (backend.CatalogSnapshot, error) {
	return backend.CatalogSnapshot{}, b.err
}

func (b failingBackend) Close() error {
	return nil
}

type recordingBackend struct {
	statement string
	result    backend.Result
}

func (b *recordingBackend) Exec(ctx context.Context, statement string) (backend.Result, error) {
	b.statement = statement
	return b.result, ctx.Err()
}

func (b *recordingBackend) Begin(ctx context.Context) (backend.Transaction, error) {
	return nil, errors.New("transaction is not implemented in recording backend")
}

func (b *recordingBackend) Catalog(ctx context.Context) (backend.CatalogSnapshot, error) {
	return backend.CatalogSnapshot{}, ctx.Err()
}

func (b *recordingBackend) Close() error {
	return nil
}

type rewriteTranslator struct {
	backendSQL   string
	sideEffects  []translator.SideEffect
	metadata     []translator.MetadataEffect
	parameters   []translator.Parameter
	handledByDev bool
}

func (t rewriteTranslator) Translate(ctx context.Context, session translator.Session, sql string) (translator.TranslationResult, error) {
	if err := ctx.Err(); err != nil {
		return translator.TranslationResult{}, err
	}
	return translator.TranslationResult{
		BackendSQL:        t.backendSQL,
		Parameters:        t.parameters,
		MetadataEffects:   t.metadata,
		SideEffects:       t.sideEffects,
		HandledByDevcloud: t.handledByDev,
	}, nil
}
